
#==============================================================================#
#                          iCount Configuration file
#                          Generated at (system time)
#==============================================================================#


#===============================     Samples     ==============================#
# Define which samples to map and which species to map to.
# Accepted species terms are: ailuropoda_melanoleuca,anas_platyrhynchos,ancestral_alleles,anolis_carolinensis,astyanax_mexicanus,bos_taurus,caenorhabditis_elegans,callithrix_jacchus,canis_familiaris,cavia_porcellus,chlorocebus_sabaeus,choloepus_hoffmanni,ciona_intestinalis,ciona_savignyi,danio_rerio,dasypus_novemcinctus,dipodomys_ordii,drosophila_melanogaster,echinops_telfairi,equus_caballus,erinaceus_europaeus,fasta,felis_catus,ficedula_albicollis,gadus_morhua,gallus_gallus,gasterosteus_aculeatus,gorilla_gorilla,homo_sapiens,ictidomys_tridecemlineatus,latimeria_chalumnae,lepisosteus_oculatus,loxodonta_africana,macaca_mulatta,macropus_eugenii,meleagris_gallopavo,microcebus_murinus,monodelphis_domestica,mus_musculus,mus_musculus_129s1svimj,mus_musculus_aj,mus_musculus_akrj,mus_musculus_balbcj,mus_musculus_c3hhej,mus_musculus_c57bl6nj,mus_musculus_casteij,mus_musculus_cbaj,mus_musculus_dba2j,mus_musculus_fvbnj,mus_musculus_lpj,mus_musculus_nodshiltj,mus_musculus_nzohlltj,mus_musculus_pwkphj,mus_musculus_wsbeij,mus_spretus_spreteij,mustela_putorius_furo,myotis_lucifugus,nomascus_leucogenys,ochotona_princeps,oreochromis_niloticus,ornithorhynchus_anatinus,oryctolagus_cuniculus,oryzias_latipes,otolemur_garnettii,ovis_aries,pan_troglodytes,papio_anubis,pelodiscus_sinensis,petromyzon_marinus,poecilia_formosa,pongo_abelii,procavia_capensis,pteropus_vampyrus,rattus_norvegicus,saccharomyces_cerevisiae,sarcophilus_harrisii,sorex_araneus,sus_scrofa,taeniopygia_guttata,takifugu_rubripes,tarsius_syrichta,tetraodon_nigroviridis,tupaia_belangeri,tursiops_truncatus,vicugna_pacos,xenopus_tropicalis,xiphophorus_maculatus

# Note that the path to the sample can be absolute or relative to the directory 
# where the Snakefile is run. 


# path or URL to sample sheet (TSV format, columns: Sample name,	Method,	Protein,	cells/tissue,	condition,	mapto,	5' barcode,	3' adapter,	linker,	comments, group)
samples: samples.tsv
# If the column "group" is present (which is optional),
# samples will be merged and output for the group calculated.

samples: data/hnRNPC_reduced.tsv
#samples: synthetic_reads_my_script_reduced.xlsx


#=============================     Parameters     =============================#
# Set the parameters for each step.
# These are set to defaults that are widely applicable to iCLIP analysis.

raw_fastq_file: data/hnRNPC.fq.gz
#raw_fastq_file: data/merge_my_script.fq.gz
adapter3: "AGATCGGAAGAGCGGTTCAG"    # original name "3'adapter"


# Annotation
release: "88"

# Demultiplex
barcode_mismatches: "0"             # number of mismatches allowed in sample barcode (default: 0)

# Quality trimm
qual_trim: "20"                       # Check if Trimming is accurate to quality and length!!!!!!!!
minimum_length: "17"

# STAR index if different genome is specified
ref:
  genome_fasta:
  # gtf file with transcripts
  annotation:
  # Overhang for STAR index
  overhang: "100"


# STAR mapp reads
mismatches: "2"                     # Number of allowed mismatches in STAR mapping (default: 2)
multimax: "10"                      # Number of allowed multiple hits (default: 10)


# Calculate cross links
groupby: "start"
quant: "cDNA"





#### Peaks configuration
#Find positions with high density of cross-linked sites.
#
#There are two typical variants of this analysis, depending on the parameters:
#
#* Gene-wise analysis, where:
#    * features = gene
#    * group_by = gene_id
#
#* Transcript-wise analysis where:
#    * features = CDS, intron, UTR3, UTR5, ncRNA, intergenic
#    * group_by = transcript_id
#  [--merge_features] [--half_window] [--fdr]


# Update releases script and Icount annotation and genome doesn't accept "--releases" word

# iCount species --source ensembl -r 88
# There are 87 species available: ailuropoda_melanoleuca,anas_platyrhynchos,ancestral_alleles,anolis_carolinensis,astyanax_mexicanus,bos_taurus,caenorhabditis_elegans,callithrix_jacchus,canis_familiaris,cavia_porcellus,chlorocebus_sabaeus,choloepus_hoffmanni,ciona_intestinalis,ciona_savignyi,danio_rerio,dasypus_novemcinctus,dipodomys_ordii,drosophila_melanogaster,echinops_telfairi,equus_caballus,erinaceus_europaeus,fasta,felis_catus,ficedula_albicollis,gadus_morhua,gallus_gallus,gasterosteus_aculeatus,gorilla_gorilla,homo_sapiens,ictidomys_tridecemlineatus,latimeria_chalumnae,lepisosteus_oculatus,loxodonta_africana,macaca_mulatta,macropus_eugenii,meleagris_gallopavo,microcebus_murinus,monodelphis_domestica,mus_musculus,mus_musculus_129s1svimj,mus_musculus_aj,mus_musculus_akrj,mus_musculus_balbcj,mus_musculus_c3hhej,mus_musculus_c57bl6nj,mus_musculus_casteij,mus_musculus_cbaj,mus_musculus_dba2j,mus_musculus_fvbnj,mus_musculus_lpj,mus_musculus_nodshiltj,mus_musculus_nzohlltj,mus_musculus_pwkphj,mus_musculus_wsbeij,mus_spretus_spreteij,mustela_putorius_furo,myotis_lucifugus,nomascus_leucogenys,ochotona_princeps,oreochromis_niloticus,ornithorhynchus_anatinus,oryctolagus_cuniculus,oryzias_latipes,otolemur_garnettii,ovis_aries,pan_troglodytes,papio_anubis,pelodiscus_sinensis,petromyzon_marinus,poecilia_formosa,pongo_abelii,procavia_capensis,pteropus_vampyrus,rattus_norvegicus,saccharomyces_cerevisiae,sarcophilus_harrisii,sorex_araneus,sus_scrofa,taeniopygia_guttata,takifugu_rubripes,tarsius_syrichta,tetraodon_nigroviridis,tupaia_belangeri,tursiops_truncatus,vicugna_pacos,xenopus_tropicalis,xiphophorus_maculatus
# Note:
# Current version of iCount is tested to work with human and rat genomes only.


#=============================     Cluster     =============================#

# Log directory when run on a cluster
logdir: "logs/cluster"
